[package]
name = "fps-settings-plugin"
version = "1.0.0"
edition = "2021"

[package.metadata.skyline]
titleid = "0100a6301214e000" # Fire Emblem Engage

[lib]
crate-type = ["cdylib"]

[dependencies]
skyline = "0.6.0"
engage-il2cpp = { git = "https://github.com/DivineDragonFanClub/engage-il2cpp", tag = "0.1.1" , features = [
    "app-basicmenu",
    "app-hubmovestatemove",
    "app-hubutil",
    "app-mess",
    "root-configbasicmenuitem",
    "system-collections-generic-dictionary_2",
    "system-collections-generic-list_1",
    "system-object",
] }
unity-nx = { git = "https://github.com/DivineDragonFanClub/unity-nx", tag = "0.1.1" }
cobapi = { git = "https://github.com/DivineDragonFanClub/cobapi", tag = "0.1.2" }
phf = { version = "0.14.0", features = ["macros"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 3